package com.ai.memory;

/**
 * Source that produced a memory entry.
 *
 * @author data-agent
 */
public enum MemorySource {

    /**
     * Explicit memory requested by the user.
     */
    USER_EXPLICIT,

    /**
     * Implicit memory inferred from user messages.
     */
    USER_IMPLICIT,

    /**
     * Memory extracted by the agent during execution.
     */
    AGENT_EXTRACTED,

    /**
     * Memory generated by system summarization or maintenance jobs.
     */
    SYSTEM_GENERATED
}
